import Head from "next/head";
import Link from "next/link";
import accomStyles from '../../styles/accom.module.css'
import { data } from "../../lib";
import { useState } from "react";




export default function Listing() {
  const [searchTerm, setSearchTerm] = useState("");
  const [listing, setListing] = useState(data)


  


  return (
    <div>
      <Head>
       
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={accomStyles.title}>Accommodations</h1>

        <input
      className={accomStyles.input}
      type="text"
      placeholder="Search by name..."
      onChange={(event) =>{
        setSearchTerm(event.target.value);
      }}

      />




      



        <div className={accomStyles.grid}>
       
            

        {data.accommodations.filter((item) =>{
            if (searchTerm == "") {
              return item
            }else if(item.name.toLowerCase().includes(searchTerm.toLowerCase())){
              return item
            }
          }).map((item) => (
              



            
             
              <Link key={item["@id"]} href={`/listing/${item["@id"]}`}>
                <a className={accomStyles.card}>

                 <h4>{item.type.name} {item.rating.label}</h4> 

                  <h2>{item.name}</h2>

                  <p>{item.description}</p>
              
               
                  
                  

                  
                 
                
                  
                <h4>Facilities</h4>
                  
                 <ul>
              {item.facilities.map((facility) => (
                   <li key={facility["@id"]}>{
                     facility.label}</li>

                    ))}
                    </ul>
                 
                </a>
                
                </Link>
                
 
              ))}
              
            
      
         
        </div>
      </main>
    </div>
  );
}
